OnlineShopping/urls.py
from django.contrib import admin
from django.urls import include, path
from website.views import *
from django.conf import settings
from django.conf.urls.static import static 
#from crudexample import urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('multipleimg/',include('multiple_upload.urls')),
    path('',home ,name='home'),
    path('placeOrder/<str:i>/',placeOrder,name='placeOrder'),
    path('login/', loginPage,name='login'),
    path('logout/', logoutPage,name='logout'),
    path('register/', registerPage,name='register'),
    path('addProduct/', addProduct,name='addProduct'),
    path('employee/',include('crudexample.urls'),name='employee'),
    path('chat/', include('chat.urls'),name='chat'),
    
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
admin.site.site_title="Learning"
admin.site.site_header="Learning"

chat/urls.py
from django.contrib import admin
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

crudexample/urls.py
from django.contrib import admin
from django.urls import path
from crudexample import views
urlpatterns =[path('emp',views.emp),
              path('show',views.show),
              path('edit/<int:id>',views.edit),
              path('update/<int:id>',views.update),
              path('delete',views.destroy)
             ]

crudexample/models.py
from django.db import models
from django.core.exceptions import ValidationError

# creating a validator function
def validate_geeks_mail(value):
    if "@gmail.com" in value:
        return value
    else:
        raise ValidationError("This field accepts mail id of google only")

class Employee(models.Model):
    eid=models.CharField(max_length=20,blank = False)
    ename=models.CharField(max_length=200,blank = False)
    email=models.EmailField(blank = False,validators =[validate_geeks_mail])
    econtact=models.CharField(max_length=50,blank = False)
    class Meta:
          db_table='employee'

crudexample/forms.py
from django import forms
from django.forms import fields
from crudexample.models import Employee
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Checkbox


class EmployeeFrom(forms.ModelForm):
    class Meta:
        model=Employee
        captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox)
        fields="__all__"

crudexample/views.py
from django.shortcuts import redirect, render
from crudexample.forms import EmployeeFrom
from crudexample.models import Employee
from django.http import JsonResponse
from django.contrib import messages
from django.conf import settings
import requests 
def emp(request):
    if request.method=='POST':
        form=EmployeeFrom(request.POST or None)
        url = 'https://www.google.com/recaptcha/api/siteverify'
        data = {
                  'secret': settings.RECAPTCHA_PRIVATE_KEY,
                  'response': request.POST.get('g-recaptcha-response')
                 }
        r=requests.post(url,data=data)
        result = r.json()
        print(result)
        if result['success']:
            if(form.is_valid()):
                try:
                    form.save()
                    messages.success(request, 'Employee information has been add.')
                    return JsonResponse({'message':'Employee information has been add.','status':'true'})
                except:
                    return JsonResponse({'message':form.errors,'status':'false'})
            else:
                return JsonResponse({'message':form.errors,'status':'false'})
            #return render(request,'crudexample/index.html',{'form':form,'errors':form.errors})                
        else:
            messages.error(request, 'Google captcha is not valid.')
    else:
        form=EmployeeFrom()
        return render(request,'crudexample/index.html',{'form':form,'errors':form.errors,'recaptcha_public_key':settings.RECAPTCHA_PUBLIC_KEY})                

def show(request):
    employees=Employee.objects.all()
    return render(request,'crudexample/show.html',{'employees':employees})

def edit(request,id):
    employee=Employee.objects.get(id=id)
    print('======>>'+settings.RECAPTCHA_PUBLIC_KEY)
    return render(request,'crudexample/edit.html',{'employee':employee,'recaptcha_public_key':settings.RECAPTCHA_PUBLIC_KEY})

def update(request,id):
    employee=Employee.objects.get(id=id)
    form=EmployeeFrom(request.POST or None,instance=employee)
    if(form.is_valid()):
        messages.success(request, 'Employee information has been updated.')
        form.save()
        return redirect("/employee/show")
    return render(request,'crudexample/edit.html',{'employee':employee,'form':form}) 

def destroy(request):
    if request.method=='POST':
        empid=request.POST.get('empid')
        if empid and empid.strip():
            employee=Employee.objects.get(id=empid)
            if employee.delete():
               messages.success(request, 'Employee has been deleted.')
            else:
               messages.error(request, 'Error has occurred.')      
    return redirect("/employee/show")    

templates/crudexample/edit.html
{% extends 'website/dependencies.html' %}
 
{% block content %}
<div class="container jumbotron">
    <p class="signup">Update Details</p>  
    <form method="POST" class="post-form cum-form" action="/employee/update/{{ employee.id }}" id='editemp'>  
    {% csrf_token %}  
<div class="container">  
<br>  
 
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Employee Id:</label>  
<div class="col-sm-4">  
    <input type="text" name="eid" id="id_eid" required maxlength="20" value="{{ employee.eid }}" {% if form.eid.errors %} class="has-emp-error" {% endif %}/>  
    {% if form.eid.errors %}
    {% for error in form.eid.errors %}
    <p class='has-error'><span> {{ error|escape }}</span></p>
    {% endfor %}
    {% endif %}
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Employee Name:</label>  
<div class="col-sm-4">  
    <input type="text" name="ename" id="id_ename" required maxlength="100" value="{{ employee.ename }}" {% if form.ename.errors %} class="has-emp-error" {% endif %}/> 
    {% if form.ename.errors %}
    {% for error in form.ename.errors %}
    <p class='has-error'><span> {{ error|escape }}</span></p>
    {% endfor %}
    {% endif %} 
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Employee Email:</label>  
<div class="col-sm-4">  
    <input type="email" name="email" id="id_eemail" required maxlength="254" value="{{ employee.email }}" {% if form.email.errors %} class="has-emp-error" {% endif %}/>  
    {% if form.email.errors %}
    {% for error in form.email.errors %}
    <p class='has-error'><span> {{ error|escape }}</span></p>
    {% endfor %}
    {% endif %} 
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Employee Contact:</label>  
<div class="col-sm-4">  
    <input type="text" name="econtact" id="id_econtact" required maxlength="15" value="{{ employee.econtact }}" {% if form.econtact.errors %} class="has-emp-error" {% endif %}/>  
    {% if form.econtact.errors %}
    {% for error in form.econtact.errors %}
    <p class='has-error'><span> {{ error|escape }}</span></p>
    {% endfor %}
    {% endif %} 
</div>  
</div> 
<div class="form-group row">  
    <label class="col-sm-2 col-form-label">&nbsp;</label>  
     <div class="col-sm-4"> 
      <script src='https://www.google.com/recaptcha/api.js?render={{ recaptcha_public_key }}'></script>
       
     </div>  
    </div>   
<div class="form-group row ml-5">  
    <div class="col-sm-4">&nbsp;</div>  
    <div class="col-sm-4">  
      <button type="submit" class="btn subbtn">Update</button>  
    </div>
    <div class="col-sm-4">&nbsp;</div>  
</div>
</div>  
</form>  
</div>
{% endblock %}

templates/crudexample/index.html
{% extends 'website/dependencies.html' %}
 
{% block content %}
{% for field in form %}
    {{ field.errors }}
{% endfor %}


<div class="container jumbotron">
    <p class="signup">Enter Details</p>
    <form method="POST" class="post-form" action="/employee/emp" id="addEmpForm">  
        {% csrf_token %}  
    <div class="container">  
    <br>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Id:</label>  
    <div class="col-sm-4">  
      {{ form.eid }}  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Name:</label>  
    <div class="col-sm-4">  
      {{ form.ename }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Email:</label>  
    <div class="col-sm-4">  
      {{ form.email }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Contact:</label>  
    <div class="col-sm-4">  
      {{ form.econtact }}  
    </div>  
  </div>
  <!--<div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Contact:</label>  
    <div class="col-sm-4">  
      {{ form.captcha }}  
    </div>  
  </div>-->  
    <div class="form-group row">  
      <label class="col-sm-1 col-form-label"></label>  
      <div class="col-sm-4">
        &nbsp;  
      </div>  
      <div class="col-sm-4">
        <script src='https://www.google.com/recaptcha/api.js?render={{ recaptcha_public_key }}'></script>  
         <button type="submit" class="btn subbtn">Submit</button>  
      </div>
      <div class="col-sm-4">
        &nbsp;  
      </div>  
  </div> 
  <div class="overlay"></div> 
    </div>  
</form>  

</div>

{% endblock %}

templates/crudexample/show.html
{% extends 'website/dependencies.html' %}
 {% block content %}

 <div class="container-fluid m-2">  
{% if messages %}
 <ul class="message list-group">
    {% for message in messages %}
    <li {% if message.tags == 'success'  %} class="list-group-item alert-success" {% elif message.tags == 'error' %}  class="list-group-item alert-danger" {% endif %}>
        {{ message }}
    </li>
   {% endfor %}
</ul>
{% endif %}
<div class="row">
    <div class="col-10">&nbsp;</div>
    <div class="col-2"><a href="/employee/emp" class="btn subbtn m-2"> Add Employee </a></div>
</div>
<table class="table table-striped table-bordered table-sm">  
    <thead class="innerheader">  
    <tr>
        <th>Employee ID</th>
        <th>Employee Name</th>
        <th>Employee Email</th>
        <th>Employee Contact</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
     
    {% if employees.count > 0 %}    
        {% for employee in employees %}
         <tr>
              <td>{{ employee.eid  }}</td>
              <td>{{ employee.ename }}</td>
              <td>{{ employee.email }}</td>
              <td>{{ employee.econtact }}</td> 
              <td>
               <a href="/employee/edit/{{ employee.id }}"><span><i class="bi bi-pencil-fill"></i></span></a>
               <a href="javascript:void(0);"><span data-empID="{{ employee.id }}"><i class="bi bi-trash"></i></span></a>
              </td> 
       </tr>
       {% endfor %}

    {% else %}
        <tr>
            <td colspan="5">
                No Record Found
            </td>
         </tr>

    {% endif %}
    </tbody>
</table>
<form method="POST"  action="/employee/delete" id="deleteEmpForm">
    {% csrf_token %} 
   <input type="hidden" name="empid" id="empid" />
</form>
</div>
{% endblock %}